### PR TITLE
README Update

### PR DESCRIPTION
**Pull request by wildtron**
- updated README.md

### CODE REVIEW

**Comment by airondumael** [comment]
question for the frontend guys. will you be using build tools? 

if so I think will need another folder for the frontend that will contain the source files and just have the public as dist. of the processed files.

**Comment by airondumael** [comment]
```
.
+-- cmd // contains build-able main packages
|    +-- api  // main package for api
|    +-- frontend // main package for frontend
|    +-- realtime // main package for realtime app (ws?)
+-- frontend // source file for the frontend
+-- core // shared packages that will be use by api and realtime
+-- api // go codes for the web api
+-- realtime // or what ever name  
+-- public // destination for the processed frontend codes 
```

suggestion for the folder structure

**Comment by wildtron** [comment]
how about we rename `cmd` to `src`?

**Comment by eshleebien** [comment]
i think better if we use `src` :+1:

**Comment by airondumael** [comment]
it's not really the whole source code. it will look like this https://github.com/gorward/todo/tree/master/cmd/webapi. 
it will only contain the main package that will call the real source codes from /api and /realtime directories.
how about bin?

**Comment by wildtron** [comment]
oke, I think if that's the case, we should remove `cmd/frontend`.

**Comment by airondumael** [comment]
yes if will use apache or nginx. I put it there because we can also use go to serve those static files by creating a simple http server inside cmd/frontend.

**Comment by eshleebien** [comment]
for static file, I guess let's use nginx/apache because they are really good at that plus we can use their caching mechanisms and other advance configurations than creating a simple http server. btw, I prefer nginx over apache.

**Comment by wildtron** [comment]
oke.. what now la? i change readme.

**Comment by wildtron** [comment]
@clevr/prime I've changed `README.md`. see if that works.

**Comment by airondumael** [comment]
:+1:

**Pull request merged**
